version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moku-dev
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lkdcode!@#
      MYSQL_DATABASE: moku-dev
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci