server:
  port: 17070

spring:
  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.boot.web.embedded.tomcat: TRACE
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
#    org.springframework.messaging: DEBUG
#    org.springframework.web.socket: DEBUG